// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using minha_agenda_minha_vida.Data;

namespace minha_agenda_minha_vida.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    [Migration("20210501180807_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("minha_agenda_minha_vida.Models.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Reuniao com a Marilene",
                            Titulo = "Reunião"
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Reuniao com a Julia",
                            Titulo = "Reunião"
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Reuniao com a Thais",
                            Titulo = "Reunião"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
