// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaAgenda.Data.Data;

namespace MinhaAgenda.Data.Migrations
{
    [DbContext(typeof(MinhaAgendaContext))]
    [Migration("20210509212253_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinhaAgenda.Domain.Models.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAgedamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Agendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAgedamento = new DateTime(2021, 5, 9, 18, 22, 53, 336, DateTimeKind.Local).AddTicks(3170),
                            Descricao = "So deus Saber...",
                            Titulo = "Sera que vou Passar?"
                        },
                        new
                        {
                            Id = 2,
                            DataAgedamento = new DateTime(2021, 5, 9, 18, 22, 53, 337, DateTimeKind.Local).AddTicks(1021),
                            Descricao = "hummmm",
                            Titulo = "Sorte Online"
                        },
                        new
                        {
                            Id = 3,
                            DataAgedamento = new DateTime(2021, 5, 9, 18, 22, 53, 337, DateTimeKind.Local).AddTicks(1033),
                            Descricao = "hummmm",
                            Titulo = "Sei não viu..."
                        },
                        new
                        {
                            Id = 4,
                            DataAgedamento = new DateTime(2021, 5, 9, 18, 22, 53, 337, DateTimeKind.Local).AddTicks(1035),
                            Descricao = "Vou Joga na mega Sena qualquer coisa...",
                            Titulo = "Então Beleza,Boa Segunda-Feira"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
